.TH LIGHTTPD 1 2003-12-21
.SH NAME
lighttpd - a fast, secure and flexible webserver
.SH SYNOPSIS
lighttpd -D -f <configfile>
.SH DESCRIPTION
.SH FILES
/etc/lighttpd/lighttpd.conf
.SH CONFORMING TO
HTTP/1.0
HTTP/1.0
HTTP-Authentification - Basic, Digest
FastCGI
CGI/1.1
.SH SEE ALSO
spawn-fcgi(1)
.SH AUTHOR
jan@kneschke.de
