Document: lighttpd
Title: Debian lighttpd Manual
Author: <insert document author here>
Abstract: This manual describes what lighttpd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lighttpd/lighttpd.sgml.gz

Format: postscript
Files: /usr/share/doc/lighttpd/lighttpd.ps.gz

Format: text
Files: /usr/share/doc/lighttpd/lighttpd.text.gz

Format: HTML
Index: /usr/share/doc/lighttpd/html/index.html
Files: /usr/share/doc/lighttpd/html/*.html

  
