/*
    CMake autogenerated config.h file. Do not edit!
*/

/* System */
#cmakedefine  HAVE_SYS_DEVPOLL_H
#cmakedefine  HAVE_SYS_EPOLL_H
#cmakedefine  HAVE_SYS_EVENT_H
#cmakedefine  HAVE_SYS_MMAN_H
#cmakedefine  HAVE_SYS_POLL_H
#cmakedefine  HAVE_SYS_PORT_H
#cmakedefine  HAVE_SYS_PRCTL_H
#cmakedefine  HAVE_SYS_RESOURCE_H
#cmakedefine  HAVE_SYS_SENDFILE_H
#cmakedefine  HAVE_SYS_SELECT_H
#cmakedefine  HAVE_SYS_SYSLIMITS_H
#cmakedefine  HAVE_SYS_TYPES_H
#cmakedefine  HAVE_SYS_UIO_H
#cmakedefine  HAVE_SYS_UN_H
#cmakedefine  HAVE_SYS_WAIT_H
#cmakedefine HAVE_SYS_TIME_H
#cmakedefine HAVE_TIME_H
#cmakedefine HAVE_UNISTD_H
#cmakedefine HAVE_PTHREAD_H
#cmakedefine HAVE_INET_ATON
#cmakedefine HAVE_IPV6

/* XATTR */
#cmakedefine HAVE_ATTR_ATTRIBUTES_H

/* mySQL */
#cmakedefine  HAVE_MYSQL_H
#cmakedefine  HAVE_LIBMYSQL

/* OpenSSL */
#cmakedefine  HAVE_OPENSSL_SSL_H
#cmakedefine  HAVE_LIBCRYPTO
#cmakedefine  OPENSSL_NO_KRB5
#cmakedefine  HAVE_LIBSSL

/* BZip */
#cmakedefine  HAVE_BZLIB_H
#cmakedefine  HAVE_LIBBZ2

/* FAM */
#cmakedefine  HAVE_FAM_H

/* getopt */
#cmakedefine  HAVE_GETOPT_H

#cmakedefine  HAVE_INTTYPES_H

/* LDAP */
#cmakedefine  HAVE_LDAP_H
#cmakedefine  HAVE_LIBLDAP

/* XML */
#cmakedefine  HAVE_LIBXML_H
#cmakedefine  HAVE_LIBXML

/* PCRE */
#cmakedefine  HAVE_PCRE_H
#cmakedefine  HAVE_LIBPCRE

#cmakedefine  HAVE_POLL_H
#cmakedefine  HAVE_PWD_H

/* sqlite3 */
#cmakedefine  HAVE_SQLITE3_H
#cmakedefine  HAVE_LIBPCRE

#cmakedefine  HAVE_STDDEF_H
#cmakedefine  HAVE_STDINT_H
#cmakedefine  HAVE_SYSLOG_H

/* UUID */
#cmakedefine  HAVE_UUID_H
#cmakedefine  HAVE_LIBUUID

/* ZLIB */
#cmakedefine  HAVE_ZLIB_H
#cmakedefine  HAVE_LIBZ

/* lua */
#cmakedefine  HAVE_LUA_H
#cmakedefine  HAVE_LIBLUA

/* inotify */
#cmakedefine  HAVE_INOTIFY_INIT
#cmakedefine  HAVE_SYS_INOTIFY_H

/* Types */
#cmakedefine  HAVE_SOCKLEN_T
#cmakedefine  SIZEOF_LONG ${SIZEOF_LONG}
#cmakedefine  SIZEOF_OFF_T ${SIZEOF_OFF_T}

/* Functions */
#cmakedefine  HAVE_CHROOT
#cmakedefine  HAVE_CRYPT
#cmakedefine  HAVE_EPOLL_CTL
#cmakedefine  HAVE_FORK
#cmakedefine  HAVE_GETRLIMIT
#cmakedefine  HAVE_GETUID
#cmakedefine  HAVE_GMTIME_R
#cmakedefine  HAVE_INET_NTOP
#cmakedefine  HAVE_KQUEUE
#cmakedefine  HAVE_LOCALTIME_R
#cmakedefine  HAVE_LSTAT
#cmakedefine  HAVE_MADVISE
#cmakedefine  HAVE_MEMCPY
#cmakedefine  HAVE_MEMSET
#cmakedefine  HAVE_MMAP
#cmakedefine  HAVE_PATHCONF
#cmakedefine  HAVE_POLL
#cmakedefine  HAVE_PORT_CREATE
#cmakedefine  HAVE_PRCTL
#cmakedefine  HAVE_PREAD
#cmakedefine  HAVE_POSIX_FADVISE
#cmakedefine  HAVE_SELECT
#cmakedefine  HAVE_SENDFILE
#cmakedefine  HAVE_SENDFILE64
#cmakedefine  HAVE_SENDFILEV
#cmakedefine  HAVE_SIGACTION
#cmakedefine  HAVE_SIGNAL
#cmakedefine  HAVE_SIGTIMEDWAIT
#cmakedefine  HAVE_STRPTIME
#cmakedefine  HAVE_SYSLOG
#cmakedefine  HAVE_WRITEV

/* libcrypt */
#cmakedefine  HAVE_LIBCRYPT

/* fastcgi */
#cmakedefine HAVE_FASTCGI_H
#cmakedefine HAVE_FASTCGI_FASTCGI_H

#cmakedefine LIGHTTPD_STATIC
