#define TK_EOL                             1
#define TK_ASSIGN                          2
#define TK_LKEY                            3
#define TK_STRING                          4
#define TK_INTEGER                         5
#define TK_LPARAN                          6
#define TK_RPARAN                          7
#define TK_COMMA                           8
#define TK_ARRAY_ASSIGN                    9
#define TK_LCURLY                         10
#define TK_RCURLY                         11
#define TK_DOLLAR                         12
#define TK_SRVVARNAME                     13
#define TK_LBRACKET                       14
#define TK_RBRACKET                       15
#define TK_EQ                             16
#define TK_MATCH                          17
#define TK_NE                             18
#define TK_NOMATCH                        19
